#!/usr/bin/env python3
"""Per (variant, bracket) confusion matrices for the transferability experiment under the 5-class
collapse, the collapsed counterpart to reports/transfer_confusion_adjudicated/ (10-class).

Reuses the reference selection, grid-identity assertion, and per-bracket prediction reading from
build_transfer_confusion.py, and the 5-class collapse, metrics, and PA/UA figure from
collapsed_5class_confusion.py. Reference and predictions are identical to the 10-class adjudicated
run: the adjudicated reviewer per location, and the temporally-matched per-bracket predictions
(pred_<bracket>_cell<id>.tif, band per variant). Scheme: Stable (all no-change classes folded,
including Other) plus Harvest, Development, Insect/Disease, and Beaver.

The five brackets use disjoint cell sets (36 cells each), so a bracket-to-bracket difference
confounds temporal transfer with the differing cell composition. These are five independent
assessments, not a controlled transfer curve; 2018_2020 is the in-sample control.

Outputs -> reports/transfer_confusion_adjudicated_5class/
  - cm_<variant>_<bracket>.csv                   25 matrices, 5x5 raw counts, reference on rows
  - cm_<variant>_<bracket>.png                   count heatmap, PA/UA margins, OA/kappa
  - transfer_metrics_long.csv                    one row per (variant, bracket, collapsed class)
  - note.md
Run scripts/plot_transfer_oa.py --dir reports/transfer_confusion_adjudicated_5class afterwards for
the OA-by-bracket figure and table.

Requires: rasterio, numpy, pandas, matplotlib
"""

import argparse
import glob
import importlib.util
import os
import re
from collections import defaultdict

import numpy as np
import pandas as pd
import rasterio


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, os.path.join(os.path.dirname(__file__), path))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


bmc = _load("bmc", "build_transfer_confusion.py")         # reference selection, grid check, per-bracket preds
cc = _load("cc", "collapsed_5class_confusion.py")          # 5-class collapse, metrics, PA/UA figure

BRACKETS = bmc.BRACKETS
CONTROL = bmc.CONTROL
BANDS = bmc.BANDS
PRED_DIR = bmc.PRED_DIR
MIN_SUP = bmc.MIN_SUP
MIN_CELLS = bmc.MIN_CELLS
NAMES5 = cc.NAMES5
LABELS5 = cc.LABELS5
CHANGE5 = [2, 3, 4, 5]
OUT = "reports/transfer_confusion_adjudicated_5class"


def _r(x):
    return round(float(x), 5) if np.isfinite(x) else ""


def write_note(chosen_desc, cells_used, skipped, long_rows):
    long = pd.DataFrame(long_rows)
    low = []
    for bracket in BRACKETS:
        sub = long[(long.bracket == bracket) & (long.variant == "v2") & long.low_support]
        low.append((bracket, [f"{r.class_name} ({r.support} px, {r.cells_present} cells)"
                              for r in sub.itertuples()]))
    lines = [
        "# transfer_confusion_adjudicated_5class",
        "",
        "Per (variant, bracket) confusion matrices for the transferability experiment under the "
        "5-class collapse, the collapsed counterpart to `reports/transfer_confusion_adjudicated/` "
        "(10-class). Generated by `scripts/build_transfer_confusion_5class.py`, reusing the reference "
        "selection and per-bracket prediction reading of `scripts/build_transfer_confusion.py` and the "
        "collapse of `scripts/collapsed_5class_confusion.py`.",
        "",
        "## Inputs",
        "",
        "- Predictions: `data/raw/transfer_predictions/<bracket>/pred_<bracket>_cell<id>.tif`, 5 bands "
        "(band1=v2 ... band5=v6), values 1 to 10, temporally matched per bracket.",
        f"- Reference: {chosen_desc}, collapsed from CKIT codes to the 5-class scheme.",
        "",
        "## Collapse",
        "",
        "Scheme: Stable (all no-change classes folded, including Other) plus Harvest, Development, "
        "Insect/Disease, and Beaver. The reference is collapsed from CKIT codes to 1..5 (Other(13) to "
        "Stable, Unknown(10) and Fire(40) dropped), and the predictions from the 10-class schema to "
        "1..5. This differs from the 10-class reference crosswalk, which drops Other(13) rather than "
        "folding it into Stable, so these collapsed matrices are the authority for the 5-class view, "
        "not a re-aggregation of the 10-class counts.",
        "",
        "## Disjoint-cell caveat",
        "",
        "The five brackets use disjoint cell sets (36 cells each, no cell shared across brackets), so a "
        "bracket-to-bracket difference confounds temporal transfer with the differing cell composition "
        "and landscape difficulty. These are five independent assessments, not a controlled transfer "
        "curve. 2018_2020 is the in-sample control, scored on its own 36 cells.",
        "",
        "## Support and low-support classes",
        "",
        "At 36 cells per bracket the change classes have few reference pixels. `transfer_metrics_long."
        "csv` carries `support` (reference pixel count per class) and `cells_present` (cells containing "
        f"the class); `low_support` fires when a class appears in fewer than {MIN_CELLS} cells or has "
        f"under {MIN_SUP} px. Low-support classes per bracket (v2, representative):",
        "",
    ]
    for bracket, lc in low:
        lines.append(f"- {bracket}: {', '.join(lc) if lc else 'none flagged'}")
    lines += [
        "",
        "## Outputs",
        "",
        "- `cm_<variant>_<bracket>.csv`: 25 matrices (5 variants x 5 brackets), 5x5 raw counts, "
        "reference on rows (diagonal is producer's accuracy), prediction on columns.",
        "- `cm_<variant>_<bracket>.png`: count heatmaps with PA/UA margins and OA/kappa.",
        "- `transfer_metrics_long.csv`: one row per (variant, bracket, collapsed class) with per-class "
        "precision, recall, F1, IoU, support, cells_present, and low_support, plus the aggregate OA, "
        "all-Stable baseline, macro-F1, mean IoU, and kappa, and a `control` flag (true for 2018_2020).",
    ]
    with open(os.path.join(OUT, "note.md"), "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--truth", default="exports/truth_selections.csv",
                    help="adjudicated reviewer per cell (matches the 10-class adjudicated run)")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)

    ref_index = bmc.build_reference_index()
    truth = bmc.load_truth(args.truth)
    chosen_ref, n_multi, missing, mismatch = bmc.choose_references_truth(ref_index, truth)
    if mismatch:
        print("STOP: truth reviewer with no matching raster:", mismatch[:10]); raise SystemExit(1)
    chosen_desc = (f"the adjudicated reviewer from {os.path.basename(args.truth)} "
                   f"({n_multi} multi-interpreted cells)")
    print(f"reference cells indexed: {len(ref_index)}   adjudicated multi-interpreted: {n_multi}")

    cms = {(v, b): np.zeros((5, 5), np.int64) for v in BANDS.values() for b in BRACKETS}
    cells_used = defaultdict(set)
    cells_present = {b: np.zeros(6, int) for b in BRACKETS}
    skipped = {"missing_ref": [], "grid_mismatch": [], "band_count": []}

    for bracket in BRACKETS:
        for pp in sorted(glob.glob(os.path.join(PRED_DIR, bracket, f"pred_{bracket}_cell*.tif"))):
            cid = bmc.pad(re.search(r"cell(\d+)\.tif$", os.path.basename(pp)).group(1))
            if cid not in chosen_ref:
                skipped["missing_ref"].append((bracket, cid))
                continue
            with rasterio.open(pp) as pds, rasterio.open(chosen_ref[cid]) as rds:
                if pds.count != 5:
                    skipped["band_count"].append((bracket, cid, pds.count))
                    continue
                ok, why = bmc.grids_match(pds, rds)
                if not ok:
                    skipped["grid_mismatch"].append((bracket, cid, why))
                    continue
                ref_raw = rds.read(1)
                ref = cc._REF_COLLAPSE[np.where((ref_raw >= 0) & (ref_raw <= 62), ref_raw, 0)]
                for k in range(1, 6):
                    if (ref == k).any():
                        cells_present[bracket][k] += 1
                for band, variant in BANDS.items():
                    cms[(variant, bracket)] += cc.cell_confusion(ref_raw, pds.read(band))
                cells_used[bracket].add(cid)

    long_rows = []
    print(f"\n{'variant':6}{'bracket':11}{'cells':>6}{'OA':>8}{'baseline':>10}{'kappa':>8}{'macroF1':>9}")
    for bracket in BRACKETS:
        for variant in BANDS.values():
            M = cms[(variant, bracket)]
            mt = cc.metrics(M)
            tot = int(M.sum())
            pd.DataFrame(M, index=LABELS5, columns=LABELS5).to_csv(
                os.path.join(OUT, f"cm_{variant}_{bracket}.csv"))
            cc.plot_rownorm(M, f"{variant} {bracket}", mt, os.path.join(OUT, f"cm_{variant}_{bracket}.png"))
            for k in range(5):
                c = k + 1
                sup = int(mt[f"support[{c}]"])
                cp = int(cells_present[bracket][c])
                low = cp < MIN_CELLS or sup < MIN_SUP
                long_rows.append(dict(
                    variant=variant, bracket=bracket, control=(bracket == CONTROL),
                    class_code=c, class_name=NAMES5[c],
                    precision=_r(mt[f"precision[{c}]"]), recall=_r(mt[f"recall[{c}]"]),
                    f1=_r(mt[f"F1[{c}]"]), iou=_r(mt[f"IoU[{c}]"]), support=sup,
                    cells_present=cp, low_support=low,
                    OA=round(mt["OA"], 5), baseline_OA=round(mt["baseline_OA"], 5),
                    macro_F1=round(mt["macro_F1"], 5), mean_IoU=round(mt["mean_IoU"], 5),
                    kappa=round(mt["kappa"], 5),
                    n_cells=len(cells_used[bracket]), total_pixels=tot))
            print(f"{variant:6}{bracket:11}{len(cells_used[bracket]):>6}{mt['OA']:>8.3f}"
                  f"{mt['baseline_OA']:>10.3f}{mt['kappa']:>8.3f}{mt['macro_F1']:>9.3f}")

    pd.DataFrame(long_rows).to_csv(os.path.join(OUT, "transfer_metrics_long.csv"), index=False)
    write_note(chosen_desc, cells_used, skipped, long_rows)
    print("\nskipped:", {k: len(v) for k, v in skipped.items()})
    print(f"wrote {OUT}/ (25 collapsed matrices, transfer_metrics_long.csv, note.md)")


if __name__ == "__main__":
    main()
